/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.2/userguide/building_java_projects.html
 */


plugins {
    // Implement Gradle plugins
    java
    id("com.github.johnrengelman.shadow") version "6.1.0"
}

// Setting some variables for our plugin!
group = "me.kokumaji"
version = "1.2-beta"

val kotlinVersion = "1.4.32"
val gradleVersion = "6.8+"

configure<JavaPluginExtension> {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

subprojects {

    apply(plugin = "java")
    apply(plugin = "com.github.johnrengelman.shadow")

    repositories {
        // Default Gradle repositories
        jcenter()
        mavenCentral()

        maven(url = "https://papermc.io/repo/repository/maven-public/")

        // This is for bStats... cuz PlaceholderAPI doesnt like
        // being shadow jar'd without it...
        maven (url = "https://repo.codemc.org/repository/maven-public")

        // Adding the Official Minecraft Repo
        maven (url = "https://libraries.minecraft.net/")

    }

    dependencies {
        // annotations
        annotationProcessor("org.projectlombok:lombok:1.18.16")
        compileOnly("org.projectlombok:lombok:1.18.16")

        // shared dependencies
        implementation("org.jetbrains:annotations:20.1.0")

        // runtime dependencies
        compileOnly("com.destroystokyo.paper:paper-api:1.16.4-R0.1-SNAPSHOT")

        // Tests - JUnit 5
        testImplementation("junit:junit:4.12")

        testImplementation("org.junit.jupiter:junit-jupiter-params:5.7.1")
        testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")
        testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.1")

        // Tests - Mocking Suite (eg. mocking Bukkit for tests)
        testImplementation("org.mockito:mockito-core:3.7.7")
        testImplementation("com.github.seeseemelk:MockBukkit-v1.16:0.25.0")
    }
}

dependencies {

    implementation(project(":warrior"))
    implementation(project(":warrior-api"))
    implementation(project(":warrior-textadv"))

}

// vv Configuring the Gradle plugins below vv

tasks {

    build {
        dependsOn("shadowJar")
    }

    compileJava {
        options.encoding = "UTF-8"
    }

    shadowJar {
        archiveClassifier.set("")

        val pkg = "me.kokumaji.warrior.libs."
        relocate("kotlin", "${pkg}kotlin")
        relocate("org.intellij", "${pkg}org.intellij")
        relocate("org.jetbrains", "${pkg}org.jetbrains")
        relocate("me.kokumaji.HibiscusAPI", "${pkg}hibiscusapi")

    }

    withType<Jar> {
        manifest {
            attributes["Main-Class"] = "me.kokumaji.warrior.textadv.TextAdventure"
        }
    }

}
