general-settings:
  plugin-prefix: "&3&lWarrior &8»"
  debug-mode: true
  use-placeholderapi: true
arena-settings:
  prevent-region-exit: true
  min-coins: 5
  max-coins: 50
lobby-settings:
  custom-spawn: true
mysql-settings:
  db-host: "localhost"
  db-port: 3306
  db-name: "warrior"
  db-user: "user"
  db-pass: "passwd"