/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dumbdogdiner.Warrior;

import org.bukkit.plugin.java.JavaPlugin;

public class Warrior extends JavaPlugin {

    @Override
    public void onEnable() {
        System.out.println("Warrior loaded successfully!");
    }

}
